[package]
name = "spool"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = [ "multipart" ] }
bytes = "1.12.1"
hex = "0.4.3"
hex-literal = "1.1.0"
infer = "0.22.0"
sha2 = "0.11.0"
sqlx = { version = "0.8", features = [ "runtime-tokio-native-tls", "postgres", "sqlite", "any" ] }
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
dbg_macro = "warn"
redundant_clone = "warn"
print_stdout = "warn"
print_stderr = "warn"
