[package]
name = "spool"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = [ "multipart" ] }
bytes = "1.12.1"
hex = "0.4.3"
hex-literal = "1.1.0"
infer = "0.22.0"
sha2 = "0.11.0"
tempfile = "3.27.0"
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "macros", "migrate"] }
serde = "1.0.229"
toml = "1.1.8"

[features]
default = ["sqlite"]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
dbg_macro = "warn"
redundant_clone = "warn"
print_stdout = "warn"
print_stderr = "warn"
